### ISSUE TITLE
Fix x and y coordinates

### ISSUE THREAD

**Issue by laura-fritschi** [maxshafer/R_tracking_analysis#2]
x and y coordinates are not comparable between individuals because the ranges are different (set by ROIs)

A solution could be to normalize the values when reading in the als files

**Comment by maxshafer** [comment]
I've updated 'loadALSfiles' so that the default behaviour is to both reverse the y axis (so low numbers mean closer to the substrate), and options for normalising either x or y, or both coordinates. Default behaviour is to normalise both.

see commit 974dad5e26098244e23d3a0a3664e8eb185d7871 for more details!
